### ISSUE TITLE
Inconsistent cycle count

### ISSUE THREAD

**Issue by GoogleCodeExporter** [rburkey2005/virtualagc#26]
```
Experimenting with AGC API I've bumped into a strange phenomenon. Running the 
agc_engine() step by step, and printing the registers before calling the 
function, I got the following result:
PendDelay:0 A:0 L:0 Z: 4000 BB:0
PendDelay:0 A:0 L:0 Z: 4001 BB:0
PendDelay:1 A:0 L:0 Z: 4001 BB:0
PendDelay:0 A:0 L:0 Z: 4001 BB:0
PendDelay:0 A:12063 L:0 Z: 4002 BB:0
PendDelay:1 A:12063 L:0 Z: 4002 BB:0
PendDelay:0 A:12063 L:0 Z: 4002 BB:0
PendDelay:0 A:0 L:0 Z: 4003 BB:12003
PendDelay:0 A:0 L:0 Z: 2563 BB:12003

The ROM image was Artemis072, so the instructions are the following:

INHINT                                         
CAF      GOBB                                  
XCH      BBANK 
TCF      GOPROG
...

The INHINT and TCF consumes 1 machine cycle correctly, but the XCH and CAF 
consumes 3 machine cycles which contradicts to the language manual. It says 
that both of these two instructions needs 2 MCT to finish. I changed line 
agc_engince.c:1891   
    State->PendDelay = i; 
to
    State->PendDelay = i-1;
with the intention to decrease the machine cycle by 1 for every multi-MCT 
instuctions. This modification doesn't have any bad effect on the scheduled 
processes, I checked V16N36 and it worked correctly.
```

Original issue reported on code.google.com by `gergo.ga...@gmail.com` on 16 Nov 2010 at 10:43

**Comment by thewonderidiot** [comment]
@indy91, @eddievhfan1984, I've been kind of wondering if this old issue is  related to the 1201s and 1202s. It would certainly lead to increases processing time, although I would have guessed the impact to be much more severe if it was right for all instructions. The relevant line looks like it has since move to 1888.

**Comment by thewonderidiot** [comment]
I'm pretty sure this issue is correct. What happens is this:

#### First call to agc_engine()
```
// Add delay for multi-MCT instructions.  Works for all instructions 
// except EDRUPT, BZF, and BZMF.  For those, an extra cycle is added
// AFTER executing the instruction -- not because it's more logically
// correct, just because it's easier.
if (!State->PendFlag)
  {
    int i;
    i = QuarterCode >> 10;
    if (State->ExtraCode)
      i = ExtracodeTiming[i];
    else
      i = InstructionTiming[i];
    if (i)
      {
        State->PendFlag = 1;
        State->PendDelay = i;
        return (0);
      }
  }
```
 For a multi-MCT instruction, say one that takes two cycles like AD, PendFlag =1, PendDelay = 1, and agc_engine() returns.

#### Second call to agc_engine()
```
  // If an instruction that takes more than one clock-cycle is in progress,
  // we simply return.  We don't do any of the actual computations for such
  // an instruction until the last clock cycle for it is reached.  
  // (Except for a few weird cases dealt with by ExtraDelay as above.) 
  if (State->PendFlag && State->PendDelay > 0)
    {
      State->PendDelay--;
      return (0);
    }
```
Both conditions are true, so PendDelay is decremented to 0 and agc_engine() returns.

#### Third call to agc_engine()
```
  if (State->PendFlag && State->PendDelay > 0)
    {
      State->PendDelay--;
      return (0);
    }
```
The second condition is no longer true, so agc_engine() doesn't return yet.

```
if (!State->PendFlag)
  {
    int i;
    i = QuarterCode >> 10;
    if (State->ExtraCode)
      i = ExtracodeTiming[i];
    else
      i = InstructionTiming[i];
    if (i)
      {
        State->PendFlag = 1;
        State->PendDelay = i;
        return (0);
      }
  }
else
  State->PendFlag = 0;
```
PendFlag is still set, so the else statement is executed. PendFlag is cleared, and instruction processing continues.

The fix suggested by Gergo correctly removes the second call to agc_engine(), making the instruction take the expected number of cycles. I'm going to go ahead and make this change.

**Comment by rburkey2005** [comment]
Sometimes you have to wonder what was running through the mind of whoever thought that little bit of idiocy up ... oh, wait!  That was me, wasn't it?  The Block 1 simulator I'm doing now works a little differently.  It just adds the amount of time associated with each instruction type directly to the MCT count.  I wonder what would have been wrong with me just doing that?  Too simple?  Had to complexify it up to make it more mysterious?  Don't know.  Surely I must have at least done some testing to see that it did what I expected ....

At any rate, it's a bit late to worry about that now.  It's awesome gergo figured it out, and that you were able to confirm it and, as you say, that it actually fixed something in the macro world!

**Comment by thewonderidiot** [comment]
Yeah man, you got showed up by a massive camel! 

(I love how Google Code now just has descriptive animal names for issue reporters.)

**Comment by thewonderidiot** [comment]
On a more serious note, I think it probably evolved from the idea that one call to agc_engine == one MCT. I take it that's not the case for the Block 1 simulator?
