### ISSUE TITLE
agc_engine_init return value wrong

### ISSUE THREAD

**Issue by GoogleCodeExporter** [rburkey2005/virtualagc#29]
```
What steps will reproduce the problem?
1. Call the function:
int res = agc_engine_init(&state, "filethatdoesnotexist", NULL, 0);

2. res should be 1, according to:
http://www.ibiblio.org/apollo/developer.html#AGC_CPU-Engine_API

3. BUT: res is equal 0 (value is overwritten in agc_engine_init.c:210  (see 
also line 193 for ROM-file-load assignment)

What version of the product are you using? On what operating system?
Last change in header: 03/30/09 RSB	Added the Downlink variable to the core 
dumps.

yaAGC-dev-20100220.tar.bz2
(same as subversion rev 609)

Also found in:
https://code.google.com/p/virtualagc/source/browse/trunk/yaAGC/agc_engine_init.c
```

Original issue reported on code.google.com by `flo.reut...@gmail.com` on 24 Sep 2014 at 8:18

**Comment by ohommes** [comment]
I see the overwrite of the value at line agc_engine_init.c:210 but I believe the reason why the return value of agc_load_binfille is ignored is because it could never return 0 as success the way it is written. I will fix agc_load_binfile and then fix the agc_engine_init to start using the return value of the agc_load_binfile.

**Comment by ohommes** [comment]
I have fixed this issue on Aug. 14 2016 per previous comment. The agc_engine_init now returns the correct values.
