### ISSUE TITLE
LGC Program Alarms

### ISSUE THREAD

**Issue by rburkey2005** [rburkey2005/virtualagc#50]
(On behalf of @indy91) There's a 1210 alarm when the LGC is first looking for landing radar data (probably) and the DSKY blanks about once per guidance cycle. Late in P63 the frequency of the DSKY blanks increases. Then in early P64 it first doesn't have new program alarms (probably while the LGC waits for the LR to move to position 2) and then enough program alarms and DSKY blanks that you barely get to see the registers. This happens in all landing programs, P64-P67.

**Comment by thewonderidiot** [comment]
Silly question, but Ron, did you ever implement RADARUPT? agc_engine.c doesn't contain the strings "RNRAD" or "radar".

**Comment by thewonderidiot** [comment]
Yeah, looks like InterruptRequests[9], which corresponds to RADARUPT, is never set anywhere. Sounds like a smoking gun, I would totally believe the software would get angry if no radar interrupts ever happen. :)

I'll work on adding support for it tonight.

**Comment by rburkey2005** [comment]
I have no recollection of it.  It's possible that I simply didn't know 
how to do it at the time, and deferred it until later.  That can be my 
new slogan:  "/The past is now!/"

**Comment by thewonderidiot** [comment]
Hahaha. 

Ah, but apparently I should be looking at NASSP's version of agc_engine.c -- they do have a function to trigger it. I wonder if it has any side effects that are missing or something.

**Comment by rburkey2005** [comment]
They use a different abstraction for i/o than the "normal" yaAGC does.  
Normal yaAGC uses a socket interface of "virtual wires" for i/o, whereas 
NASSP uses a set of API functions of the same name, I believe, but I 
have no knowledge beyond that of what's coming in or going out over them.

**Comment by indy91** [comment]
It's still very likely a NASSP problem. There are some strange things going on, for example, when the frequency of the DSKY blanking increases in late P63 and you manually set the LR positon to 2 (hover) then the frequency is about 2 seconds again. RADARUPTs are generated as soon as the LGC asks for range data at 40k feet. I don't have much knowledge about that either, but a lot of the interrupt and I/O stuff is happening outside of agc_engine.c

**Comment by rburkey2005** [comment]
I can well believe it, and (frankly) hope you're right.  But it doesn't 
alter the fact that none of it was ever tested in yaAGC, and 
consequently yaAGC is suspect. Without a strategy for isolating the 
problem to either NASSP or yaAGC, it's difficult to know how much more 
time to spend on it and yet not dismiss it completely.

Is there any reasonable way to isolate it?

-- Ron

**Comment by indy91** [comment]
We have the alarm data for the 1210 alarm:

V05 N08

R1: 3722
R2: 70000

@eddievhfan1984 translated this in this post: http://www.ibiblio.org/mscorbit/mscforum/index.php?topic=491.msg24213#msg24213 As he said the DAP becomes sluggish, but guidance was a separate problem and is now very good despite the 1210 alarms. Once our landing radar is generating range and velocity information (right now everything else should work including all the LGC interaction) and they are properly processed landings should be possible with the LGC.

**Comment by indy91** [comment]
The 1210 alarms are solved. They had to do with the interaction between the landing radar and the LGC. After range/velocity data is requested and read from the LR/RR the RadarActivity bit is set to 0. This wasn't done before. There also was a workaround for the radar test mode which prohibited velocity data to be read later in Program 63, which was the second cause of the 1210 alarms. The workaround was probably necessary because the RadarActivity bit wasn't reset. This is now done in the Landing Radar code.

Guidance was not affected by the 1210 alarm, so even without landing radar data our LM in NASSP came pretty close to land on the Moon using the Virtual AGC. Due to various errors (IMU alignment, state vector propagation etc.) the LGC at the time of landing had an altitude error of about 400 ft and  5 ft/s. I simply used a biased landing site vector to account at least for the altitude error and the LGC went into Program 65 at the end of Program 64 and it completely automatic landed on the Moon. Doing this with the Virtual AGC has been a dream of mine for a long time, @rburkey2005  thank you so much for making it possible!

To stay more on topic, there is still a program alarm happening during descent also ascent. It's a 401 and doesn't seem to do any harm and other than the 1210 alarm it also doesn't lock me out of the DSKY. Here the alarm data:

V05 N08
R1: 3757
R2: 60066

No attitude in gimbal lock is commanded at all, so a 401 alarm really shouldn't happen. This seems more like a Virtual AGC problem than the 1210 alarm, which was pretty much 99% a NASSP problem.

**Comment by rburkey2005** [comment]
Thanks!  Except for the little bit at the end (for which I think I create a new issue, so as to close out this one), I'd normally say that's the best news I've heard today.  As it happens, though, it has been an unusual day, so I'll just say that that's _very good_.

(And by the way, you're welcome, it's what I always wanted to, even if just vicariously. :-) )
