### ISSUE TITLE
Program alarm error from LGC during descent and ascent.

### ISSUE THREAD

**Issue by rburkey2005** [rburkey2005/virtualagc#52]
There is still a program alarm happening during descent and also ascent. It's a 401 and doesn't seem to do any harm and other than the 1210 alarm it also doesn't lock you out of the DSKY. Here the alarm data:

V05 N08
R1: 3757
R2: 60066

No attitude in gimbal lock is commanded at all, so a 401 alarm really shouldn't happen. This seems more like a Virtual AGC problem than the 1210 alarm #50 , which was pretty much 99% a NASSP problem.

**Comment by thewonderidiot** [comment]
The alarm we're hitting is this one:

http://www.ibiblio.org/apollo/listings/Luminary099/FINDCDUW--GUIDAP_INTERFACE.agc.html#414C41524D4D4741

The code leading up to it is:
		CA	MPAC +2		# LIMIT THE MGA
		TS	L		# CAN'T LXCH:  NEED UNLIMITED MGA FOR ALARM
		CA	CDUZDLIM
		TC	LIMITSUB	# YIELDS LIMITED MGA.  1 BIT ERROR POSSIBLE
		XCH	MPAC +2		# 	BECAUSE USING 2'S COMP.  WHO CARES?
		EXTEND
		MSU	MPAC +2		# THIS BETTER YIELD ZERO
		EXTEND
		BZF	+2
		TCF	ALARMMGA

The fact that it's preceded immediately by an MSU makes me dubious about the new MSU implementation's correctness on all inputs, despite its passage of the now-believed-to-be-correct Smally test for it.

LIMITSUB is another suspect. It's doing some division to limit the magnitude of the value in L to the limit in A. We know for a fact that there's at least one case (L = 0, A and divisor have the same magnitude) in which yaAGC and the hardware sim sometimes disagree. Anyways, it looks like the best path forward will be to just try to find the exact number passed in to the above code is when the alarm gets triggered and comparing results. I'll get working on that. @indy91, is there a fast and easy way that you know of to make the 0401s happen?

**Comment by thewonderidiot** [comment]
Ehhh, following along more with the logic here, I don't think the division in LIMITSUB is likely to be the culprit. A is forced to +0, so the magnitude can't be the same. Still, this whole little chunk is standalone, so I should be able to set up some test cases for it in Validation. If that doesn't turn up anything suspicious, it must be a bad value for the middle gimbal angle making it into this logic.

**Comment by thewonderidiot** [comment]
Okay, I've identified a difference between the hardware sim and yaAGC in a particular case of this code. When MPAC+2 contains 77777 (-0 or -1 depending on whether we're using 2's complement at this point), yaAGC triggers a 401 alarm and the hardware sim does not. It seems to me that yaAGC's behavior here is incorrect, as the alarm shouldn't be triggered on any negative number until -14345.

The difference does indeed come from the divide instruction. What's being executed in this case is:
> +0-0  /   +14344

The hardware sim receives 77777 in its A register as the quotient; yaAGC receives 00000. Since this is DV, I'd really rather not do a full control pulse analysis to prove one or the other right, but I can if it comes to that.

@eddievhfan1984 or @indy91 -- based on what you guys know about the code here, is it reasonable for 77777 to be requested as the gimbal angle here?

**Comment by eddievhfan1984** [comment]
I don't believe so. The CDUs should only be registering in positives with accumulator wrap-around. That's how it's stored in erasable memory, anyways.

**Comment by thewonderidiot** [comment]
Actually the description above is a bit incorrect, the remainder in L appears to also get set to match the sign of the dividend, and *this* is the difference that matters that's causing the alarm in the test case.

Hrrrrrm. I think it's worth trying this anyways, since it is a behavioral discrepancy capable of causing a 401. I'm going to open a pull request with a patch for DV make yaAGC match the hardware sim. If the 401s still happen, then we can delete the pull request and I'll go back to the drawing board.
